apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fp529911f-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:62dbff2eca562b729081651c8ae8561e3833bf71@sha256:553916821bef20afdfa42d6bdd9ed4aa0ff7da7aa038a9331e6574f47c9ae2a3
          name: container-image
